### ISSUE TITLE
안드로이드 클린 아키텍쳐 모듈 구성

### ISSUE THREAD

**Issue by Donghyeon0915** [DEU-Smiley/Smiley-Android-App#1]
## 📝 Description
클린 아키텍쳐 도입을 위해 presentation, domain, data 모듈로 다중 모듈 환경을 구성

## 📍 Todo
- [ ] presentation 모듈 구성 (app 모듈을 presentation 모듈로 변경)
- [ ] domain 모듈 구성
- [ ] data 모듈 구성
