### ISSUE TITLE
디자인, 확장 함수 등 기타 수정 사항 반영

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#101]
## 📝 Description
> 기타 수정 사항 반영

## 📍 Todo
- [x] ViewPager 여백 잘리는 부분 수정
- [x] 확장 함수 추가
- [x] BottomSheet + CoordinatorayLayout 테두리 적용 안되던 부분 수정

## 🔗 Reference
