### ISSUE TITLE
블루투스 기기 연결 기능 구현

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#117]
## 📝 Description
> 블루투스 기기 검색 목록에서 장치 연결 시 해당 장치와 연결
> 데이터 수신까지 확인하기

## 📍 Todo
- [x] 기기 클릭 이벤트 구현
- [ ] 기기 연결 로딩 이미지 추가
- [x] 기기 연결 로직 구현
- [x] 블루투스 데이터 수신 구현

## 🔗 Reference

**Comment by dongx0915** [comment]
# 2023-05-04 할 일

- 블루투스 검색 결과 RecyclerView의 아이템 클릭 시 해당 아이템에만 Loading 아이콘 표시 되도록 설정
- 연결이 완료 되거나, 실패한 경우 Loading 아이콘 다시 숨기기
- 연결할 때 동안은 클릭 이벤트 비활성화
- 검색 버튼도 비활성화

### 고려 사항
- 각 아이템 뷰에 로딩 아이콘을 띄우는 게 아닌 기존 로딩 아이콘 그대로 사용하는 방법 고려
