### ISSUE TITLE
Adapter, 에러 처리 리팩토링

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#118]
## 📝 Description
> Adapter의 클릭 이벤트 리스너 공통으로 분리
> 에러 처리 커스텀 다이얼로그로 띄우도록 수정
> 의약품 요청 로직 리팩토링

## 📍 Todo
- [ ] Adapter의 클릭 이벤트 리스너 공통으로 분리
- [ ] 에러 처리 커스텀 다이얼로그로 띄우도록 수정
- [ ] 의약품 요청 로직 리팩토링

## 🔗 Reference
