### ISSUE TITLE
프로젝트 리펙토링

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#129]
## 📝 Description
> 프로젝트 리펙토링 목록
> 생각날 때마다 적어놓고 하나씩 진행할 예정

## 📍 Todo
- [ ] Fragment Destory 될 때 bind 인스턴스 제거
- [ ] ViewModel에 StateFlow 값 변경하는 부분 메소드화
- [ ] 각 State 클래스 네이밍 규칙 일관화
- [x] handler 처리 observer에서 바로 수행 (handleStateChange를 별도로 만들지 않음)
- [ ] Error 다이얼로그에 에러 메세지 출력 형식 가공 필요
- [ ] 타임라인 뷰는 모듈로 분리
- [ ] 이미지 로딩 Glide 사용 고려
- [ ] BaseFragment 생성 (TransparentTouchLIstner 포함)

## 🔗 Reference

**Comment by dongx0915** [comment]
# 완료한 리팩토링은 아래에 기록
