### ISSUE TITLE
매거진 요청 기능 구현

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#138]
## 📝 Description
> 서버로부터 매거진 요청 기능 구현
> 최상위 2개만 가져와서 홈 화면에 표시

**매거진 서버는 임시로 Mock 서버를 이용**

## 📍 Todo
- [x] 매거진 요청 기능 구현
- [x] 매거진 조회 화면 구현
- [ ] Glide 추가
- [x] 타임라인 뷰 애니메이션 추가

## 🔗 Reference
