### ISSUE TITLE
화면 디자인 일부 수정

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#140]
## 📝 Description
> 일부 디자인 적 요소 수정

- 권한 요청 화면에서 안내 문구가 길어 애매하게 잘리는 상황 발생
- 바텀 시트의 테두리 부분이 너무 둥글어서 이질감이 듦 (상단바와 차이가 많이 생겨 이질감이 듦)
- 앱 아이콘 변경
- 일일 미션 배너 사이즈 유동적으로 조절

## 📍 Todo
- [ ] 앱 아이콘 변경
- [ ] 바텀 시트 테두리 Radius 수정
- [ ] 권한 요청 문구 수정
- [ ] 일일 미션 배너 사이즈 조절

## 🔗 Reference
