### ISSUE TITLE
Auto Release 작동 테스트

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#15]
## 📝 Description
> Auto Release 작동 테스트

## 📍 Todo
- [x] relase 브랜치 생성
- [x] main으로 pull-request 요청
- [x] release가 자동으로 생성되는지 확인

## 🔗 Reference

**Comment by dongx0915** [comment]
main으로 push 될 때 릴리즈를 생성하도록 변경

2023-03-24 09:22 테스트 완료
