### ISSUE TITLE
교정기 착용 시간 측정 기능 구현

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#156]
## 📝 Description
- 교정기 착용 시간 측정 기능 구현
- 홈 화면 프로그레스바에 표시
- 일일 미션에도 반영
- 교정기 착용 여부 판별 ( 알림 또는 화면에 표시하는 방법 중 택 1 )

## 📍 Todo
- [ ] bluetoothViewModel의 착용 시간을 홈 화면에 반영 (Flow 사용하면 될 듯)
- [ ] 일일 미션에 착용 시간 반영
- [ ] 홈 화면에서 당일 착용 시간 가져와서 초기화
- [ ] 교정기 착용 감지 보여줄 방식 설정

## 🔗 Reference

**Comment by dongx0915** [comment]
# 유의사항

- 장치 등록 화면과 메인 화면들이 다른 액티비티에서 동작하는 상황이므로, 뷰모델 공유가 힘듦
- 블루투스 등록 화면을 메인 액티비티로 옮기는 방안을 검토해봐야할 듯

### 로직 변경
- 회원 가입 -> 교정 정보 등록 -> 장치 등록 -> 메인 화면 순서이지만,
- 회원 가입 -> 교정 정보 등록 -> 메인 화면 -> 장치 등록 안내 순서로 변경해야할 듯
