### ISSUE TITLE
병원 바텀시트 디자인 수정 + 바텀시트 behavior 적용

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#171]
## 📝 Description
병원 바텀시트 디자인 수정
BottomSheetFragmentDialog 대신에 bottom_sheet_behavior를 통해 구현

## 📍 Todo
- [ ] 바텀시트 디자인 수정
- [ ] 바텀시트 behavior 적용
- [ ] 바텀시트 전체화면 구현
- [ ] 바텀시트 MotionLayout 적용

## 🔗 Reference
