### ISSUE TITLE
홈 화면 데이터 연결

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#179]
## 📝 Description
홈 화면 데이터 연결

## 📍 Todo
- [x] Glide 도입
- [x] 주변 제휴 치과 데이터 연결
- [x] 유튜브 추천 영상 데이터 연결
- [ ] 매거진 타임라인 제거 & 디자인 변경

## 🔗 Reference
