### ISSUE TITLE
AI 자가진단 & 의약품 성분 검사 화면 구현

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#191]
## 📝 Description
AI 자가 진단 & 의약품 성분 검사 화면 구현

## 📍 Todo
- [ ] AI 자가진단 화면 추가
- [ ] 의약품 성분 검사 화면 추가
- [ ] BlueView 라이브러리 추가

## 🔗 Reference
