### ISSUE TITLE
멀티 모듈 gradle 중복 제거

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#20]
## 📝 Description
> Clean Architecture를 적용함으로써 각 모듈의 build.gradle이 중복되는 상황 발생
> 프로젝트 최상단에 common.gradle을 생성하여 중복되는 부분을 제거

## 📍 Todo
- [x] common.gradle 작성
- [x] 각 모듈 build.gradle 중복 제거

## 🔗 Reference
https://github.com/HeeGyeong/ModuleArchitecture/blob/main/CleanArchitectureStudy/test-dependencies.gradle
https://github.com/HeeGyeong/CleanArchitectureSample/blob/main/CleanArchitectureStudy/data/build.gradle

https://heegs.tistory.com/60
https://heegs.tistory.com/110

**Comment by dongx0915** [comment]
# 추가
common.gradle을 Project 범위의 gradle에서 추가하는 방식으로 진행하면 Project 범위의 gradle은 하위 모든 Module 범위의 gradle에 공통적으로 적용되기 때문에 dependencies와 compileSdkVersion 등 빼낼 수 없는 코드들이 생김

> common.gradle을 Project 범위의 gradle에 apply하는 것이 아닌, 각 Module의 gradle에 apply하는 방식으로 적용


# 📍 Todo
- [x] core-dependencies.gradle 추가
- [x] ext-version.gradle 추가
- [x] 각 모듈에 apply

**Comment by dongx0915** [comment]
## Multi Module 프로젝트의 gradle 중복 제거 중 발생했던 오류들 

### Failed to query the value of property 'namespace' 에러

각 모듈의 Manifest.xml 파일에 packge가 지정되어 있지 않아서 발생한 에러

각 모듈의 Manifest.xml 파일에 package 부분을 선언해준다. 

libary 모듈의 경우 자신의 모듈명, application 모듈일 경우 프로젝트의 명을 작성하면 된다.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example.data">
```

<hr>

### Type BuildConfig is defined multiple times 에러

https://stackoverflow.com/questions/60507686/type-buildconfig-is-defined-multiple-times

각 모듈의 Manifest.xml 에서 package 이름을 모듈 이름으로 지정해줘야한다. (전부 똑같이 지정해서 발생한 문제)

<hr>

### shrinkResourceError - Removing unused resources requires unused code shrinking to be turned on. 에러

common.gradle에서 buildTypes 안에 release 부분에 shrinkResources true로 설정되어 있다.

minifyEnabled까지 true로 설정해줘야 에러가 안난다.

```groovy
            release {
                if(isApplicationPlugin){
                    shrinkResources true
                }
                minifyEnabled true  -> 여기도 true로 설정
                proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            }
```

**Comment by Donghyeon0915** [comment]
참고 : 
https://heegs.tistory.com/60
https://heegs.tistory.com/110
