### ISSUE TITLE
빌드 시 서명된 앱이 추출되도록 앱 서명 작성

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#33]
## 📝 Description
> 현재 빌드시 서명 되지 않은 unsigned.apk가 추출되고 있음
> release로 추출 시 앱이 설치가 되지 않음
> > 서명된 앱을 추출할 수 있도록 common.gradle에 앱 서명 작성

## 📍 Todo
- [x] keystore.properties에 서명 정보 추가
- [x] common.gradle에서 불러온 후 release로 빌드 시 해당 서명을 이용하도록 작성
- [x] workflows에서 빌드 전 서명 정보를 작성하도록 수정

## 🔗 Reference

**Comment by dongx0915** [comment]
# Secrets 변수 안들어오는 문제

Settings에서 Repository Secret에 넣어줘야 정상적으로 불러와짐

Environment Secret에 넣으니 읽어오지 못해서 빈 칸이 들어가는 경우 발생

# STORE_FILE 경로 문제

로컬에선 ../Smiley.jks 로 작성해줘야 했지만, workflows에선 Smiley.jks로 작성해주면 된다.

아래와 같이 수정

```yml
    # Generate keystore.properties
    - name: Generate keystore.properties
      env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        STORE_FILE: ${{ secrets.STORE_FILE }}
      run: |
        echo storePassword=$STORE_PASSWORD > ./keystore.properties
        echo keyPassword=$KEY_PASSWORD >> ./keystore.properties
        echo keyAlias=$KEY_ALIAS >> ./keystore.properties
        echo storeFile=$STORE_FILE >> ./keystore.properties
```
