### ISSUE TITLE
안드로이드 클린 아키텍쳐 패키지 디렉토리 구성

### ISSUE THREAD

**Issue by Donghyeon0915** [DEU-Smiley/Smiley-Android-App#4]
## 📝 Description
클린 아키텍쳐 구조에 맞게 패키지 디렉토리 구성
Feature 관련된 패키지는 추후 기능 개발할 때 생성

## 📍 Todo
- [ ] presetation 모듈에 common, main, App.kt 추가
- [ ] domain 모듈에 common/base 추가
- [ ] data 모듈에 common/module, common/utils 추가
