### ISSUE TITLE
프로젝트 리팩토링 및 확장 함수 추가

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#43]
## 📝 Description
> 클래스 역할 별로 패키지를 구분하고, 필요 없는 메소드 제거
> Presentation 계층에서 공통적으로 필요한 확장 함수 추가

## 📍 Todo
- [x] onboarding 패키지 클래스별로 패키지 생성
- [x] OnBoardingActivity 클래스에 setContentView 메소드 제거
- [x] 확장 함수 추가

## 🔗 Reference
