### ISSUE TITLE
디자인 변경 사항 수정

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#55]
## 📝 Description
> 로그인 화면 상단 텍스트는 사용자 설정에 관계 없이 일정한 크기를 보여주는게 좋다고 판단
> 앱의 컨셉을 드러내는 문구라 크기가 작아지면 안됨
> 로그인 배너 부분 sp -> dp로 수정
> 로그인 버튼 폰트 크기 조정
> 버튼 하단 여백 수정
> 글자 행간 지정
> 온보딩 버튼 그림자 제거

![image](https://user-images.githubusercontent.com/63500239/228262351-c9c71b8d-2a0e-46a6-9f89-d40f76b3118c.png)

## 📍 Todo
- [x] sp -> dp 변경
- [x] 로그인 버튼 폰트 크기 조절
- [x] 버튼 하단 여백 28 -> 36
- [x] 글자 행간 지정

## 🔗 Reference

**Comment by dongx0915** [comment]
# 글자 행간(lineSpacingExtra) 이슈

피그마에서 행간을 지정하는 Line Height 속성과 안드로이드에서 행간을 지정하는 lineSpacingExtra의 단위가 다름

계산 방법이 있는 듯 하지만 LineHeight 22 기준으로 lineSpacingExtra 8sp로 기준을 잡음

일단은 LineHeight가 2씩 줄어들 때마다 lineSpacingExtra로 2씩 줄이도록 지정
