### ISSUE TITLE
디자인 수정 사항 반영

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#69]
## 📝 Description
> 디자인 수정 사항 반영

### 1. 줄바꿈 제거
- 문장 끝에 \n 을 넣어서 문장이 구분되도록 구현했으나, 가로 폭이 좁거나 폰트를 크게 쓰는 경우 사진과 같은 현상 발생

![image](https://user-images.githubusercontent.com/63500239/229289516-c32579ac-3a53-405c-9823-8a8a0753d474.png)

### 2. 행간 조절 & 폰트 컬러
- 폰트 기본 여백이 있어서 행간이 넓어지는 것이라 추측 됨
- 폰트 기본 여백을 제거해야 할 듯함
- 한 줄 텍스트에도 기본적으로 LineSpacingExtra 옵션 추가 ( 다른 요소들과의 간격이 달라질 수 있음 )

- 폰트 컬러도 디자인이랑 살짝 다르므로 수정 필요

<div display="flex">
<img src = "https://user-images.githubusercontent.com/63500239/229289604-9420358f-3c74-4e2a-9b05-b7c6083d5052.png"/>
<img src = "https://user-images.githubusercontent.com/63500239/229289623-0af84c7c-8354-46e1-b41a-8579cdb07b21.png"/>
</div>

## 📍 Todo
- [x] 온보딩 텍스트 줄바꿈 제거
- [x] 행간 조절 ( 폰트 기본 여백 제거 )
- [x] 폰트 컬러 수정
- [x] 고정 텍스트는 strings.xml에 선언
- [x] 폰트 디자이너분이 지정해준 양식대로 dimens.xml에 선언

## 🔗 Reference

**Comment by dongx0915** [comment]
# 로그인 화면 텍스트 크기 고정

로그인 상단의 텍스트는 고정 크기로 보여주기로 했으나,
텍스트 크기 선언 부분을 ```dimens.xml```로 분리하는 과정에서 고정 크기의 텍스트도 변경 되어버림
-> 수정 필요
