### ISSUE TITLE
네트워크 관련 클래스 작성

### ISSUE THREAD

**Issue by dongx0915** [DEU-Smiley/Smiley-Android-App#77]
## 📝 Description
> 네트워크 통신에 관련된 클래스들을 작성
> 응답을 받기 위한 Wrapper 클래스
> 응답을 도메인 계층으로 전달하기 위한 BaseResult.kt 
> 통신을 위한 Retrofit, Okhttp 객체 생성 및 hit 모듈 작성

## 📍 Todo
- [x] WrapperListResponse, WrappterResponse 클래스 작성
- [x] BaseResult 클래스 작성
- [x] Retrofit 의존성 추가
- [x] Retrofit, Okhttp 객체 생성 hilt 모듈 작성

## 🔗 Reference
